image: alpine:3.17

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - sonarCheck
  - deploy

.before_script_template:
  before_script:
    - apk add --update maven

unit-test-job:   # This job runs in the test stage.
  extends: .before_script_template
  stage: test
  script:
    - echo "Running unit tests..."
    - mvn test
  allow_failure: true

sonarqube-check:
  extends: .before_script_template
  stage: sonarCheck
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/code/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
     - .sonar/cache
  script:
    - echo "Installing node.js..."
    - apk add --update nodejs
    - echo Running sonar analysis for ${SONAR_PROJECT_KEY}
    - mvn -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.projectName="${CI_PROJECT_NAME} ${GITLAB_USER_NAME}" --fail-at-end verify sonar:sonar
  allow_failure: true

build site:
  image: node:6
  stage: build
  script:
    - cd ./frontend
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy:
  image: alpine:3.17
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ user@server.com:/your/project/path/
